### ISSUE TITLE
Danger + swiftLint + Github actions

### ISSUE THREAD

**Issue by miguelpimentel** [Escola-em-Casa/ios-escola-em-casa#2]
**Issue:** #[002]

 **Descrição da nova feature**

Adicionar CI com análise estática de código

 **Descrição de como ela funciona**

Para PR's abertos é executada a análise estática do código apresentando warnings, comentários sobre PR's e até bloquear a pipeline de deploy

**Comment by laercios** [comment]
Opa Miguel, acredito que isso foi resolvida, então vou fechar essa issue.
